#!/usr/bin/env bash
# install nginx server.

apt-get -y update
apt-get -y install nginx
chown -R ubuntu /var/www
echo -e "Hello World!" > /var/www/html//var/www/html/index.html
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx start
