#!/usr/bin/env bash
# Configure your Nginx server so that \
# redirect_me is redirecting to another page.

ADD301_REDIRECT="\\\tlocation /redirect_me {return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;}"

sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.original
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i '30i ADD301_REDIRECT' /etc/nginx/sites-available/default
sudo service nginx restart
