#!/usr/bin/env bash
# Configure your Nginx server so that \
# redirect_me is redirecting to another page

link="https://www.youtube.com/watch?v=QH2-TGUlwu4"
config="\\\trewrite ^/redirect_me $link permanent;"

sudo apt-get update
sudo apt-get -y install nginx

sudo mkdir /usr/share/nginx/html
sudo touch /usr/share/nginx/html/index.html
echo "Hello World!" > /usr/share/nginx/html/index.html
sudo sed -i "30i $config" /etc/nginx/sites-available/default
sudo service nginx start
