#!/usr/bin/env bash
#Displays numbers from 1 to 100
#Displays FizzBuzz when the number == multiple of 3 and 5
#Displays Fizz when the number == multiple of 3
#Displays Buzz when the number == multiple of 5

for num in {1..100};
do
    if [ $((num % 15)) -eq 0 ]; then
	echo "FizzBuzz"
    elif [ $((num % 3)) -eq 0 ]; then
	echo "Fizz"
    elif [ $((num % 5)) -eq 0 ]; then
	echo "Buzz"
    else
	echo "$num"
    fi
done