#!/usr/bin/env bash
#loops from 1 to 1
#Displays bad luck for the 4th loop iteration
#Displays good luck for the 8th loop iteration
#Displays Best School for the other iterations

i=1

while [ "$i" -lt 11 ];
do
if [ "$i" == 4 ]; then
    echo "bad luck"
  elif [ "$i" == 8 ]; then
    echo "good luck"
  else
    echo "Best School"
  fi

  i=$((i + 1))
done
