#!/usr/bin/env bash
#loops from 1 to 1
#Displays bad luck for the 4th loop iteration
#Displays good luck for the 8th loop iteration
#Displays Best School for the other iterations

i=1
while [ $i -lt 9 ]
do
  echo "Best School"
  if [ $i == 3 ]
    then
        echo "bad luck"
    fi

  if [ $i == 6 ]
    then
        echo -e "good luck"
    fi
    
  i=$(( i + 1 ))
done
